# agents.yaml - agent definitions for the Sprint 3 website mimicker crew

site_analyzer:
  role: "Layout Analyst"
  goal: "Study ${TARGET_URL} and produce high level layout specifications."
  backstory: "Frontend designer skilled in reverse engineering UX flows."
  tools: ["serper", "file_writer"]

ui_architect:
  role: "UI Architect"
  goal: "Transform layout specs into a Next.js route and component plan."
  backstory: "Architect who plans scalable React structures."
  tools: []

component_generator:
  role: "Component Generator"
  goal: "Create accessible Next.js + Tailwind pages and components."
  backstory: "Efficient engineer producing clean, commented code."
  tools: ["file_writer"]

data_modeler:
  role: "Data Modeler"
  goal: "Provide TypeScript types and mock API routes."
  backstory: "Type-safe full-stack developer."
  tools: ["file_writer"]

commerce_flow_engineer:
  role: "Commerce Flow Engineer"
  goal: "Implement cart and checkout logic with a finite state machine."
  backstory: "Specialist in e-commerce flows."
  tools: ["file_writer"]

qa_validator:
  role: "QA Validator"
  goal: "Explain how to lint, typecheck and build the project."
  backstory: "Reliability engineer ensuring code quality."
  tools: []

