/**
 * Home page route.
 * Provides the landing experience and wires in the hero section generated by the crew.
 * The hero showcases a split layout to mimic the analyzed site's aesthetic.
 */
import type { Metadata } from 'next'
import { Hero } from '../../../components/organisms/Hero'

/**
 * Basic SEO metadata so crawlers understand the purpose of the page.
 */
export const metadata: Metadata = {
  title: 'Home',
  description: 'Landing page generated by the Website Mimicker crew'
}

export default function HomePage() {
  return (
    <main className="p-4">
      {/* <auto-gen start: crew-site-mimicker> */}
      <Hero
        heading="Welcome Aboard"
        text="This hero layout mirrors the target site's structure using placeholder content."
      />
      {/* Additional home sections would be generated here */}
      {/* <auto-gen end: crew-site-mimicker> */}
    </main>
  )
}
