/**
 * Category listing page.
 * Adds URL-synchronised filters so users can drill down on category items.
 * Used when navigating to /category/[slug].
 */
import Link from 'next/link'
import type { Metadata } from 'next'
import CategoryFilters from '../../../components/molecules/CategoryFilters'

/** Metadata for the category page; title is static to avoid leaking target content. */
export const metadata: Metadata = {
  title: 'Category',
  description: 'Category listing generated by the Website Mimicker crew'
}

interface CategoryPageProps {
  params: { slug: string }
  searchParams: Record<string, string | string[] | undefined>
}

export default function CategoryPage({ params, searchParams }: CategoryPageProps) {
  const { slug } = params
  return (
    <main className="p-4 space-y-4">
      {/* <auto-gen start: crew-site-mimicker> */}
      <h1 className="text-xl font-bold">Category: {slug}</h1>
      {/* Client-side filters synchronise state with the URL */}
      <CategoryFilters />
      <p className="text-sm text-gray-600">Filters: {JSON.stringify(searchParams)}</p>
      {/* Placeholder for category products */}
      {/* <auto-gen end: crew-site-mimicker> */}
      <p className="mt-4"><Link href="/">Back home</Link></p>
    </main>
  )
}
