/**
 * Hero component rendering a split layout with text and image placeholder.
 * Added to provide a reusable hero section generated by the crew for the home page.
 * Used in app/(routes)/(home)/page.tsx.
 */
'use client'

import type { FC } from 'react'

/** Props for {@link Hero}. */
export interface HeroProps {
  /** Headline text displayed on the left column. */
  heading: string
  /** Supporting copy displayed under the heading. */
  text: string
}

/**
 * Displays a responsive hero with text on the left and an image placeholder on the right.
 * The image is intentionally a gray box so no copyrighted media is shipped.
 */
export const Hero: FC<HeroProps> = ({ heading, text }) => {
  return (
    <section
      aria-label="Hero"
      className="flex flex-col items-center gap-6 py-8 md:flex-row"
    >
      {/* Text column */}
      <div className="flex-1 space-y-2">
        <h1 className="text-4xl font-bold">{heading}</h1>
        <p>{text}</p>
      </div>
      {/* Image placeholder column */}
      <div
        className="flex-1 h-64 w-full bg-gray-200"
        aria-hidden="true"
      />
    </section>
  )
}
